### ISSUE TITLE
error MSB3323: Unable to find manifest signing certificate in the certificate store.

### ISSUE THREAD

**Issue by 0xorOne** [0xb11a1/yetAnotherObfuscator#1]
compile error

**Comment by 0xb11a1** [comment]
have you change or add any options to the compiler ?

**Comment by 0xb11a1** [comment]
@0xorOne Try this go to project > yetAnotherObfuscator properties > signing > turn off "Sign the ClickOnce manifests", and tell me if it's working now

**Comment by 0xorOne** [comment]
I compiled it using github action

```
cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\"
.\MSBuild.exe $Env:GITHUB_WORKSPACE\SQLRecon\SQLRecon\SQLRecon\SQLRecon.csproj /property:Configuration=Release
```

**Comment by 0xb11a1** [comment]
I think the error because signing was enabled, i change it in the dev branch, can you check if this fixes the issue ?
